name: Build an apk

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g react-app

      - name: Run script
        run: |
          chmod +x .bin/build-android.sh
          bash .bin/build-android.sh
